### ISSUE TITLE
Localhost is not working

### ISSUE THREAD

**Issue by benzvera** [Spiess/cottontaildb-python-client#14] opened 2022-04-26 08:12 UTC
I wrote a script using cottontaildb-python-client and started Cottontail DB locally on my laptop. To use the client, I had to use an external IP address instead of localhost (on Windows).

**Comment by Spiess** [comment] 2022-04-26 08:42
Unfortunately I cannot reproduce this issue on macOS.
All combinations of CLI and script usage with `localhost` and `127.0.0.1` work in my tests.

Could you provide more information on your issue?
If this is a Windows specific issue, could you find out what might be causing the problem and if there are known solutions or workarounds?

**Comment by benzvera** [comment] 2022-04-26 14:57
I think it is not possible to connect to Cottontail DB. Unfortunately, I could not find out what the problem could be.

This is the information of the terminal:

Traceback (most recent call last):
  File "my_script.py", line 15, in <module>
    list = client.query('cineast', 'cineast_segment', proj, where)
  File "/mnt/c/Users/verab/OneDrive/Desktop/UniBas/6_Semester/Bachelorarbeit/cottontaildb-python-client/cottontaildb_client/cottontaildb_client.py", line 361, in query
    return [r for response in responses for r in self._parse_query_response(response)]
  File "/mnt/c/Users/verab/OneDrive/Desktop/UniBas/6_Semester/Bachelorarbeit/cottontaildb-python-client/cottontaildb_client/cottontaildb_client.py", line 361, in <listcomp>        
    return [r for response in responses for r in self._parse_query_response(response)]
  File "/home/vera/.local/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/vera/.local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1650984500.913843100","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line
":3128,"referenced_errors":[{"created":"@1650984500.913841000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"

**Comment by silvanheller** [comment] 2022-05-04 15:13
I cannot reproduce this issue on Windows 10, with or without VPN. I suggest to close it  (Especially as there are workarounds) and maybe somebody in the future who encounters it again can re-open it.

**Closed as completed** 2022-05-04 17:40 UTC
